name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: bun/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18.20.8
        cache: "bun"

    - shell: bash
      run: bun add -g turbo

    - shell: bash
      run: bun install
