# Default labels
- name: "breaking change"
  color: "b60205"

- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "dependencies"
  color: "1d76db"
  description: "Pull requests that update a dependency file"

- name: "DO NOT MERGE"
  color: "b60205"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "good first issue"
  color: "fe9b9c"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "ignore for release"
  color: "bfd4f2"
  description: "Exclude from Release Notes"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "work in progress"
  color: "e5d19e"

# Type labels
- name: "@type/ci"
  color: "ededed"

- name: "@type/docs"
  color: "ededed"
  from_name: "documentation"

- name: "@type/feature"
  color: "ededed"

- name: "@type/fix"
  color: "ededed"

- name: "@type/improve"
  color: "ededed"

# Top Package labels
- name: "@apps/backend"
  color: "e261d6"
  description: "Backend development"

- name: "@apps/frontend"
  color: "f89c0f"
  description: "Frontend development"

# Core Package labels
- name: "@core/common"
  color: "e99695"

- name: "@core/data"
  color: "50D413"

- name: "@core/database"
  color: "88651D"

- name: "@core/datastore"
  color: "1997D2"

- name: "@core/designsystem"
  color: "936116"

- name: "@core/domain"
  color: "DC79FD"

- name: "@core/model"
  color: "D1A70E"

- name: "@core/network"
  color: "630D81"

- name: "@core/testing"
  color: "29033D"

# Feature Package labels
- name: "@feature/top"
  color: "c22752"

- name: "@feature/auth"
  color: "48360E"
