blank_issues_enabled: false
contact_links:
  - name: X (Twitter)
    url: https://x.com/tatsutakein
    about: Please ask and answer questions here.
  - name: Instagram
    url: https://instagram.com/tatsutakein
    about: Please ask and answer questions here.
