name: "Assign author to Pull request"

on:
  pull_request:
    types: [ opened ]

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/marketplace/actions/assign-author
      - name: Assign Author
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1.6.2
