name: 'Checks'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    uses: ./.github/workflows/wc-changed.yml

  check-actions:
    uses: ./.github/workflows/wc-check-actions.yml
    needs: changed
    if: needs.changed.outputs.actions == 'true'

  check-frontend:
    uses: ./.github/workflows/wc-check-frontend.yml
    needs: changed
    if: needs.changed.outputs.frontend == 'true'

  codeql:
    uses: ./.github/workflows/wc-codeql.yml
    needs: changed
    if: needs.changed.outputs.codeql == 'true'

  status-check:
    runs-on: ubuntu-24.04
    needs:
      - check-actions
      - check-frontend
      - codeql
    permissions: { }
    if: failure()
    steps:
      - run: exit 1
